apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1
  version: "1.31"

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    amiFamily: "Bottlerocket"
    tags:
      costid: iac
      createdby: eksctl


addonsConfig:
  disableDefaultAddons: true

addons:
  - name: vpc-cni # no version is specified so it deploys the default version
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest # auto discovers the latest available: 