apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  #   service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  gatewayClassName: cilium
  # infrastructure:
  #   annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  #     service.beta.kubernetes.io/aws-load-balancer-type: external
  listeners:
  - protocol: HTTP
    port: 80
    name: web-gw
    allowedRoutes:
      namespaces:
        from: All

