apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway
    namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    - method: GET
    - method: POST
    - method: PATCH
    - method: DELETE
    backendRefs:
    - name: backend-service
      port: 80
      

