apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: "/mnt/data"