apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: VPCLink
metadata:
  name: nlb-internal
spec:
  name: nlb-internal
  securityGroupIDs: 
    - sg-0ffca432d1d0cd36e
  subnetIDs: 
    - subnet-00a6ead832cea0f87
    - subnet-07c2cd6daa5ef2a58
